from setuptools import setup, find_packages

setup(
    name="microbiome-analysis",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "numpy>=1.21.0",
        "pandas>=1.3.0",
        "scikit-learn>=1.0.0",
        "scipy>=1.7.0",
        "matplotlib>=3.4.0",
        "seaborn>=0.11.0",
        "plotly>=5.3.0",
        "xgboost>=1.5.0",
        "lightgbm>=3.3.0",
        "imbalanced-learn>=0.8.0",
        "h5py>=3.6.0",
        "requests>=2.26.0",
        "fastapi>=0.68.0",
        "uvicorn>=0.15.0",
        "python-multipart>=0.0.5",
        "pydantic>=1.8.0",
        "tqdm>=4.60.0",
        "python-dotenv>=0.19.0",
        "loguru>=0.5.3",
        "mkdocs>=1.2.0",
        "mkdocs-material>=7.2.0",
        "pytest>=6.2.0",
        "pytest-cov>=2.12.0",
        "prometheus-client>=0.11.0",
        "grafana-api>=1.0.0",
        "pyyaml>=5.1"
    ],
    extras_require={
        'shap': ['shap>=0.40.0'],
    },
    python_requires=">=3.8",
    author="Your Name",
    author_email="your.email@example.com",
    description="A comprehensive microbiome analysis package",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/yourusername/microbiome-analysis",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Topic :: Scientific/Engineering :: Bio-Informatics",
    ],
) 